### ISSUE TITLE
display groups command

### ISSUE THREAD

**Issue by edo-dc** [Brianetta/StickyLocks#10]
Add the /sl group command to the help file. (it shows all created groups).
And perhaps change that command to /sl group**s**

**Comment by Brianetta** [comment]
I suppose the group command should show `[group]` instead of `<group>` to show that this parameter is optional.

I could alias **groups** to **group**, although this would just be sugar, and wouldn't go into the help.

**Comment by Brianetta** [comment]
Fixed by fa2f346448a055da7912c181342bb3b29c0ca011
