### ISSUE TITLE
Players can lock oak fence gates, but not the variants.

### ISSUE THREAD

**Issue by Phyther** [Brianetta/StickyLocks#12]
How do I add variants of an item like fence gates to the config?

**Comment by Phyther** [comment]
Added:
[variant]_FENCE_GATE
for each of the types.

**Comment by Brianetta** [comment]
Yeah, the new fence gates were added to the [default config](https://raw.githubusercontent.com/Brianetta/StickyLocks/master/src/main/resources/config.yml). You probably upgraded after running an older version.
