### ISSUE TITLE
Will you update to include 1.14 blocks

### ISSUE THREAD

**Issue by OldmanLP85** [Brianetta/StickyLocks#16]
It would be nice to be able to lock the new blocks as well. In particular the barrels, and more importantly the lecterns. Allow others to view book, but not take it. Not sure if it’s doable, but would be very beneficial in multiplayer servers. 

Thanks for your awesome plugin.

**Comment by Brianetta** [comment]
Yeah, those were added in a9c182c30f5e822ddd201780444299074f60fa2f

**Comment by OldmanLP85** [comment]
Oh sweet, thanks for the fast reply :) I’ll have to check it out.
